[package]
name = "bevychat-client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_egui = "0.36.0"
bevy_http_client = "0.8.3"
bevy_spacetimedb = "1.0.0"
bevy_ui_text_input = "0.5.2"
open = "5.3.2"
spacetimedb-sdk = "1.3.2"